version: "3"
services:
  app:
    build: ../
    ports:
      - 3000:3000
    env_file:
      - ../config/app.env
    restart: always
  db:
    ports:
      - 3306:3306
    env_file:
      - ../config/db.env
    restart: always
